services:
  frontend:
    build: 
      context: apache/Dockerfile
    ports:
      - 80:80

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - volume_db:/data/db

volumes:
  volume_db:
    name: "volume_db"

networks:
  network1:
    # config
  network2:
    # config