services:
  frontend:
    build: 
      context: apache/Dockerfile
    ports:
      - 80:80


  #frontend:
    # description du service
  database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# ...autant d'autres services que necessaire
volumes:
  volume1:
  #config
  volume2:
  #config

networks:
  network1:
  # config
  network2:
  # config