services:
  frontend:
    build: 
      dockerfile: apache/Dockerfile
    container_name: frontend
    ports:
      - 80:80

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - volume_db:/data/db

volumes:
  volume_db:
    name: "volume_db"

#networks:
 # network1:
    # config
  #network2:
    # config