version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
